### ISSUE TITLE
Set up mdoc for documentation

### ISSUE THREAD

**Issue by lenguyenthanh** [grokking-vietnam/grox#61]
[mdoc - Typechecked markdown documentation for Scala](https://scalameta.org/mdoc/)

**Comment by akizminet** [comment]
Cái mdoc này nó sẽ generate ra 1 thư mục khác nên mình định là dùng với docusaurus hay là generate ra markdown thôi anh. Nếu generate ra markdown thì cần thay đổi cấu trúc thư mục, 1 source và 1 target.

**Comment by lenguyenthanh** [comment]
Em thấy kiểu nào hay hơn? Anh thấy nếu làm được cái docusaurus thì làm luôn.

**Comment by akizminet** [comment]
> Em thấy kiểu nào hay hơn? Anh thấy nếu làm được cái docusaurus thì làm luôn.

Vậy em sẽ làm cái docusaurus anh
